//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyVeXemPhimTrucTiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUNGGIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHUNGGIO()
        {
            this.LICHCHIEUx = new HashSet<LICHCHIEU>();
        }
    
        public string MA_KHUNGGIO { get; set; }
        public System.TimeSpan GIOBATDAU { get; set; }
        public System.TimeSpan GIOKETTHUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHCHIEU> LICHCHIEUx { get; set; }
    }
}
