//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyVeXemPhimTrucTiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHCHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICHCHIEU()
        {
            this.VEs = new HashSet<VE>();
        }
    
        public string MA_LICHCHIEU { get; set; }
        public string MA_PHIM { get; set; }
        public string MA_PHONG { get; set; }
        public string MA_KHUNGGIO { get; set; }
        public System.DateTime NGAYCHIEU { get; set; }
        public Nullable<decimal> GIATVE_PHUTROI { get; set; }
    
        public virtual KHUNGGIO KHUNGGIO { get; set; }
        public virtual PHIM PHIM { get; set; }
        public virtual PHONGCHIEU PHONGCHIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE> VEs { get; set; }
    }
}
