//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyVeXemPhimTrucTiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIM()
        {
            this.LICHCHIEUx = new HashSet<LICHCHIEU>();
            this.THELOAIs = new HashSet<THELOAI>();
        }
    
        public string MA_PHIM { get; set; }
        public string TEN_PHIM { get; set; }
        public Nullable<int> THOILUONG { get; set; }
        public Nullable<System.DateTime> NGAYKHOICHIEU { get; set; }
        public string MOTA { get; set; }
        public string POSTER { get; set; }
        public string DAO_DIEN { get; set; }
        public string DIEN_VIEN { get; set; }
        public string GIOI_HAN_TUOI { get; set; }
        public string TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHCHIEU> LICHCHIEUx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THELOAI> THELOAIs { get; set; }
    }
}
