//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyVeXemPhimTrucTiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE
    {
        public string MA_VE { get; set; }
        public string MA_KHACH { get; set; }
        public string MA_LICHCHIEU { get; set; }
        public string MA_GHE { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public decimal TONGTIEN { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual GHE GHE { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LICHCHIEU LICHCHIEU { get; set; }
    }
}
